### ISSUE TITLE
求新增山东地区支持

### ISSUE THREAD

**Issue by FrostN0v0** [ZM25XC/nonebot_plugin_auto_teenstudy#1]
plz

**Comment by ZMXC01** [comment]
本学期大学习要结束了，暂时停更，暑假我会陆续写好全国其他地区，将在9月份进行大更新。敬请期待！

**Comment by ZM25XC** [comment]
山东地区暂时无解

**Comment by ZM25XC** [comment]
山东地区只有单人使用版，多人提交暂时没办法，单人使用版前往https://github.com/ZM25XC/commit_dxx
