### ISSUE TITLE
git pull更新无法覆盖

### ISSUE THREAD

**Issue by forchannot** [ZM25XC/nonebot_plugin_auto_teenstudy#10]
因为data文件中有众多json文件，而这些文件都是会不断被覆盖或者更新的，在执行git pull时会导致冲突而无法更新，建议分离data文件夹，使用nonebot提供的公共data文件夹来存放数据

**Comment by ZM25XC** [comment]
1、目前data文件夹中的json文件只有dxx_answer.json会在每次更新时更新到最新。
2、dxx_answer.json文件更不更新都无所谓，插件会在每星期一9:00启动更新，自动更新到最新一期
3、git pull时提示冲突，可依次执行以下命令:
git stash
git pull 
git stash pop
