### ISSUE TITLE
大学习的期数不是最新的

### ISSUE THREAD

**Issue by Karensky** [ZM25XC/nonebot_plugin_auto_teenstudy#11]
停留在16期

**Comment by ZM25XC** [comment]
我每次更新插件都会同步更新前最新一期的数据
![image](https://user-images.githubusercontent.com/78628186/189582324-d5abc3a2-2b07-457e-8918-8fba80e23602.png)
![image](https://user-images.githubusercontent.com/78628186/189582342-7648863c-e16c-47af-a0b6-a547e269efad.png)
如果错过了每周一9:00的自动检查更新，请使用 更新大学习 或 推送大学习 指令手动更新到最新一期

**Comment by Karensky** [comment]
![Screenshot_2022-09-12-14-32-07-037_com sonelli juicessh](https://user-images.githubusercontent.com/59323207/189588025-ad6982d7-e2f8-4e1c-bc17-19c8c9047f53.jpg)
输入更新大学习没有反应

**Comment by ZM25XC** [comment]
更新大学习和推送大学习功能为需要更新至0.1.3以上版本
请检查插件是否为最新版
插件更新指令：pip install nonebot-plugin-auto-teenstudy -U

**Comment by ZM25XC** [comment]
请安装lxml库，指令：pip install lxml 或使用清华源：pip install -i https://pypi.tuna.tsinghua.edu.cn/simple lxml
