### ISSUE TITLE
输入更新大学习没有反应

### ISSUE THREAD

**Issue by Karensky** [ZM25XC/nonebot_plugin_auto_teenstudy#12]
![Uploading Screenshot_2022-09-12-14-32-07-037_com.sonelli.juicessh.jpg…]()

**Comment by ZM25XC** [comment]
更新大学习和推送大学习功能为需要更新至0.1.3以上版本
请检查插件是否为最新版
插件更新指令：pip install nonebot-plugin-auto-teenstudy -U
国内源：pip install -i https://pypi.tuna.tsinghua.edu.cn/simple nonebot-plugin-auto-teenstudy -U
