### ISSUE TITLE
错误信息Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

### ISSUE THREAD

**Issue by Karensky** [ZM25XC/nonebot_plugin_auto_teenstudy#13]
![-3f7ebb964397e7fb](https://user-images.githubusercontent.com/59323207/189590047-bcc3458c-3e7b-494a-9d5b-937d419dd25a.png)

**Comment by ZM25XC** [comment]
请安装lxml库
指令：pip install -i https://pypi.tuna.tsinghua.edu.cn/simple lxml
