### ISSUE TITLE
添加省份信息失败

### ISSUE THREAD

**Issue by Karensky** [ZM25XC/nonebot_plugin_auto_teenstudy#14]
![Uploading IMG_20220912_164409.jpg…]()

**Comment by Karensky** [comment]
![Uploading IMG_20220912_164409.jpg…]()

**Comment by Karensky** [comment]
现实没有支持

**Comment by Karensky** [comment]
![Uploading -2881d90fb17c3d7.png…]()

**Comment by ZM25XC** [comment]
哪个省份
![image](https://user-images.githubusercontent.com/78628186/189611878-f56ca432-daee-4f3a-9383-601125c306ff.png)

**Comment by Karensky** [comment]
湖北省，江西省都不行，没更新之前可以

**Comment by ZM25XC** [comment]
1、江西省，这两个星期不统计大学习完成情况，没法添加很正常。
2、湖北地区没问题，麻烦你看看湖北地区的使用方式和插件更新日志，添加用户的方式改了
