### ISSUE TITLE
/添加大学习#湖北#……还是不行

### ISSUE THREAD

**Issue by Karensky** [ZM25XC/nonebot_plugin_auto_teenstudy#15]
指令应该是对的，显示添加失败，该地区暂未支持，不止湖北，江西浙江上海都不行

**Comment by ZM25XC** [comment]
麻烦反馈添加信息截图

**Comment by Karensky** [comment]
离谱，图片发不出来

**Comment by Karensky** [comment]
2896311434麻烦加一下

**Comment by ZM25XC** [comment]
![image](https://user-images.githubusercontent.com/78628186/189616431-c4b2d9b1-c451-4b37-b9b5-378522bf6a5c.png)
![image](https://user-images.githubusercontent.com/78628186/189616542-89058ce7-de75-4012-9940-ba83298235a0.png)
