### ISSUE TITLE
河南的有么

### ISSUE THREAD

**Issue by like977** [ZM25XC/nonebot_plugin_auto_teenstudy#2]

**Comment by ZMXC01** [comment]
暂时不支持，现在停更。本学期大学习要结束了，下次更新在九月份，我会加上河南地区，敬请期待。

**Comment by ZM25XC** [comment]
河南文件已写，待测试

**Comment by like977** [comment]
> 河南文件已写，待测试

有电报群吗？想学习下，看了你blog抓湖南的数据，河南的是在微信里面调用的（open·······），不知道怎么解决了

**Comment by ZM25XC** [comment]
那个openid抓一次就行，之后一直用那个openid就行

**Comment by like977** [comment]
> 那个openid抓一次就行，之后一直用那个openid就行

那个写好的文件开源吗？

**Comment by ZM25XC** [comment]
测试完会开源

**Comment by like977** [comment]
> 测试完会开源

学到了很多，感谢贡献！

**Comment by ZM25XC** [comment]
import requests

# 以下信息需要自己手动抓取
cookie = ""

# 以下获取最新一期大学习id
get_new_study_headers = {
    "Host": "hnqndaxuexi.dahejs.cn",
    "Connection": "keep-alive",
    "accept": "*/*",
    "User-Agent": "Mozilla/5.0 (Linux; Android 12; M2007J3SC Build/SKQ1.220303.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.99 XWEB/3262 MMWEBSDK/20220204 Mobile Safari/537.36 MMWEBID/6170 MicroMessenger/8.0.20.2100(0x28001438) Process/toolsmp WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm64",
    "Content-Type": "application/json",
    "X-Requested-With": "com.tencent.mm",
    "Referer": "http://hnqndaxuexi.dahejs.cn/study/studyList",
    "Accept-Encoding": "gzip, deflate",
    "Accept-Language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
    "Cookie": cookie
}
get_new_study_url = "http://hnqndaxuexi.dahejs.cn/stw/news/list?&pageNumber=1&pageSize=10"
response = requests.get(url=get_new_study_url, headers=get_new_study_headers)
response.encoding = response.apparent_encoding
dxx_list = response.json()['obj']['news']['list'][0]
newsid = dxx_list['id']
dxx_name = dxx_list['title']
# 以下链接获取用户详细信息
get_user_headers = {
    "Host": "hnqndaxuexi.dahejs.cn",
    "Connection": "keep-alive",
    "Content-Length": "2",
    "accept": "*/*",
    "User-Agent": "Mozilla/5.0 (Linux; Android 12; M2007J3SC Build/SKQ1.220303.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.99 XWEB/3262 MMWEBSDK/20220204 Mobile Safari/537.36 MMWEBID/6170 MicroMessenger/8.0.20.2100(0x28001438) Process/toolsmp WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm64",
    "Content-Type": "application/json",
    "Origin": "http://hnqndaxuexi.dahejs.cn",
    "X-Requested-With": "com.tencent.mm",
    "Referer": "http://hnqndaxuexi.dahejs.cn/study/personalSet",
    "Accept-Encoding": "gzip, deflate",
    "Accept-Language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
    "Cookie": cookie
}
params = {
}
get_user_info_url = "http://hnqndaxuexi.dahejs.cn/stw/front-user/info"
response = requests.post(url=get_user_info_url, headers=get_user_headers, json=params)
response.encoding = response.apparent_encoding
token = response.json()['obj']['openId']
# 以下获取最新一期大学习详细信息
news_info_headers = {
    "Host": "hnqndaxuexi.dahejs.cn",
    "Connection": "keep-alive",
    "Content-Length": "26",
    "accept": "*/*",
    "User-Agent": "Mozilla/5.0 (Linux; Android 12; M2007J3SC Build/SKQ1.220303.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.99 XWEB/3262 MMWEBSDK/20220204 Mobile Safari/537.36 MMWEBID/6170 MicroMessenger/8.0.20.2100(0x28001438) Process/toolsmp WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm64",
    "Content-Type": "application/json",
    "Origin": "http://hnqndaxuexi.dahejs.cn",
    "X-Requested-With": "com.tencent.mm",
    "Referer": "http://hnqndaxuexi.dahejs.cn/study/gohome",
    "Accept-Encoding": "gzip, deflate",
    "Accept-Language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
    "Cookie": cookie
}
params = {
    "newsld": newsid
}
news_info_url = "http://hnqndaxuexi.dahejs.cn/stw/news/info"  # 带参数newsid
response = requests.post(url=news_info_url, headers=news_info_headers, json=params)
response.encoding = response.apparent_encoding
commit_url = f"http://hnqndaxuexi.dahejs.cn/stw/news/study/{newsid}"
commit_headers = {
    "Host": "hnqndaxuexi.dahejs.cn",
    "Connection": "keep-alive",
    "accept": "*/*",
    "User-Agent": "Mozilla/5.0 (Linux; Android 12; M2007J3SC Build/SKQ1.220303.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.99 XWEB/3262 MMWEBSDK/20220204 Mobile Safari/537.36 MMWEBID/6170 MicroMessenger/8.0.20.2100(0x28001438) Process/toolsmp WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm64",
    "token": token,
    "Content-Type": "application/json",
    "X-Requested-With": "com.tencent.mm",
    "Referer": "http://hnqndaxuexi.dahejs.cn/study/studyList",
    "Accept-Encoding": "gzip, deflate",
    "Accept-Language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
    "Cookie": cookie
}
response = requests.post(url=commit_url, headers=commit_headers)
response.encoding = response.apparent_encoding
print(response.json())

**Comment by ZM25XC** [comment]
河南地区测试完毕，下次更新将同步

**Comment by ZM25XC** [comment]
过两天更新，最近比较忙，抓取一次cookie后就不要再进河南官方大学习平台，不然cookie会刷新

**Comment by ZM25XC** [comment]
河南地区已更新

**Comment by like977** [comment]
> 河南地区已更新

cookie有效期好像只有一天

**Comment by ZM25XC** [comment]
> > 河南地区已更新
> 
> cookie有效期好像只有一天

不止一天，你抓取到了cookie,就别进官方公众号了，不然cookie会刷新

**Comment by like977** [comment]
> > > 河南地区已更新
> > 
> > cookie有效期好像只有一天
> 
> 不止一天，你抓取到了cookie,就别进官方公众号了，不然cookie会刷新

大佬测试多久更新了吗？具体时长多少

**Comment by ZM25XC** [comment]
> > > > 河南地区已更新
> > > 
> > > 
> > > cookie有效期好像只有一天
> > 
> > 
> > 不止一天，你抓取到了cookie,就别进官方公众号了，不然cookie会刷新
> 
> 大佬测试多久更新了吗？具体时长多少

暑假测试的，别进公众号，一两个月没问题

**Comment by like977** [comment]
> > > > > 河南地区已更新
> > > > 
> > > > 
> > > > cookie有效期好像只有一天
> > > 
> > > 
> > > 不止一天，你抓取到了cookie,就别进官方公众号了，不然cookie会刷新
> > 
> > 大佬测试多久更新了吗？具体时长多少
> 
> 暑假测试的，别进公众号，一两个月没问题

测试了几天，cookie返回参数是需要重新认证，也就是说一天一更新啊。

**Comment by ZM25XC** [comment]
短时间内不要频繁提交，容易让cookie失效。如果cookie的时效很短，目前来说没啥解决办法，只有抓包，cookie目前无解。
