### ISSUE TITLE
无法载入插件

### ISSUE THREAD

**Issue by ddwr1** [ZM25XC/nonebot_plugin_auto_teenstudy#20]
![QQ图片20220923175541](https://user-images.githubusercontent.com/58874234/191937900-e7760321-1d15-45e9-8fd8-a15d27b64759.png)

**Comment by ZM25XC** [comment]
请安装nonebot官方定时任务插件nonebot_plugin_apscheduler
指令 pip install nonebot_plugin_apscheduler
github仓库：https://github.com/nonebot/plugin-apscheduler
