### ISSUE TITLE
安徽有机会吗

### ISSUE THREAD

**Issue by forchannot** [ZM25XC/nonebot_plugin_auto_teenstudy#8]

**Comment by ZM25XC** [comment]
安徽写好了，我正在写其他省份的，大概过一个星期就更新
![image](https://user-images.githubusercontent.com/78628186/187201093-e1b1b111-f680-48b3-b8dd-6c09adc5c66a.png)

**Comment by forchannot** [comment]
> 安徽写好了，我正在写其他省份的，大概过一个星期就更新 ![image](https://user-images.githubusercontent.com/78628186/187201093-e1b1b111-f680-48b3-b8dd-6c09adc5c66a.png)

好的，大佬辛苦了

**Comment by ZM25XC** [comment]
安徽地区已更新

**Comment by forchannot** [comment]
> 安徽地区已更新

![MI)_47{3~$5~~AEOPRI_5_X](https://user-images.githubusercontent.com/100580891/188361779-76db848b-5d4a-4894-839a-75a6d060e267.PNG)
报错error怎么回事呢，格式是添加大学习#安徽#{
"username":"xxx",
"token":"xxx",
"gender":"x",
"mobile":"xxx",
"level1":"xxx",
"level2":"xxx",
"level3":"xxx",
"level4":"xxx",
"level5":""
}

**Comment by ZM25XC** [comment]
![image](https://user-images.githubusercontent.com/78628186/188367528-1f3ce43e-161c-4a59-ab82-73691da01632.png)
这个文件下加上这行，token参数忘记传了，dxx_list.json里面在个人信息也加个"token":"xxxxxx"

**Comment by forchannot** [comment]
> ![image](https://user-images.githubusercontent.com/78628186/188367528-1f3ce43e-161c-4a59-ab82-73691da01632.png) 这个文件下加上这行，token参数忘记传了，dxx_list.json里面在个人信息也加个"token":"xxxxxx"

可以了，还有最新不是第18期了吗，但是程序才16期

**Comment by ZM25XC** [comment]
![image](https://user-images.githubusercontent.com/78628186/188528687-46c99b63-7ba5-49c6-914b-3031f5a25364.png)
156行更改成这样即可，本次大学习更新后，测试出很多bug，目前已修复，等待下次更新
